#!/bin/bash

. test_helper.bash

exec $FIREBUILD_PREFIX_CMD firebuild \
  -c ../etc/firebuildrc \
  -o 'env_vars.pass_through += "GCOV_PREFIX"' \
  -o 'env_vars.pass_through += "GCOV_PREFIX_STRIP"' \
  -o "ignore_locations += \"$GCOV_PREFIX\"" \
  "$@"
