#!/bin/sh

set -e

find . -name '*.gcno' | grep -v /gcov/ | while read f; do
    mkdir -p gcov/$(dirname $f)
    ln -sf $(realpath $f) gcov/$f
done

lcov -q -c -d . --no-external -o gcov/tmp.info
lcov -q -r gcov/tmp.info -o gcov/coverage-incl-tests.info '*.pb.*' '*interceptor/gen_*.*'
genhtml -o gcovhtml gcov/coverage-incl-tests.info
lcov -q -r gcov/coverage-incl-tests.info -o gcov/coverage-excl-tests.info '*/test/*.c*'
echo "Line coverage rate, excluding test files:"
lcov --summary gcov/coverage-excl-tests.info 2>&1 | grep '^  lines' | sed 's/  lines.*: \([^%]*\)%.*/\1/'
