#!/bin/sh

set -e

find . -name '*.gcno' | grep CMakeFiles/ | while read f; do
    cp $f $(dirname $f| xargs dirname | xargs dirname)/$(basename $f)
done
lcov -q -c -d . --no-external -o tmp.info
lcov -q -r tmp.info -o coverage-incl-tests.info '*.pb.*'
genhtml coverage-incl-tests.info
lcov -q -r coverage-incl-tests.info -o coverage-excl-tests.info '*/test/*.c*'
echo "Line coverage rate, excluding test files:"
lcov --summary coverage-excl-tests.info  2>&1 | grep '^  lines' | sed 's/  lines.*: \([^%]*\)%.*/\1/'
