#!/bin/bash

set -e

if [ -e CMakeCache.txt ]; then
    echo "Please remove generated cmake files from the top dir" >&2
    exit 1
fi

build_dir="${1:-build-self-dir}"

mkdir ${build_dir}-first-build
cd ${build_dir}-first-build
cmake ..
make all
cd test
export PATH="${PATH/ccache/ccache-DISABLED/}"
mkdir ../../$build_dir
./run-firebuild -- env -C ../../$build_dir cmake ..
./run-firebuild -- make -C ../../$build_dir clean
time ./run-firebuild -- make -C ../../$build_dir all

