name: CI

on: [pull_request]

env:
  BUILD_DEPS: cmake libconfig++-dev libevent-dev libprotobuf-dev protobuf-compiler libxxhash-dev pkg-config python3-jinja2
  TEST_DEPS: bats node-d3 graphviz moreutils
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: install-deps
      run: |
        sudo add-apt-repository -y -u ppa:rbalint/valgrind
        sudo add-apt-repository -y -u ppa:rbalint/xxhash
        sudo apt-get -y install $BUILD_DEPS $TEST_DEPS doxygen valgrind lcov
    - name: build-out-of-tree
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make -j2
    - name: doc
      run: |
        cd build
        doxygen
    - name: build-in-tree
      run: |
        cmake -DCMAKE_BUILD_TYPE=Debug .
        make -j2
    - name: test
      # tests don't run with out of tree builds at the moment
      run: |
        make check
        test/close_fds_exec make valgrind-check
    - name: coverage
      # tests don't run with out of tree builds at the moment
      run: |
        git clean -dxf
        cmake -DCOVERAGE=1 .
        make -j2
        make check coverage-info
        [ $(echo "$(make coverage-info | grep '^[\.0-9]*$') >= 67.3" | bc) = 1 ]
  scan-build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: install-deps
      run: |
        sudo cp .github/workflows/llvm-snapshot.gpg.key /etc/apt/trusted.gpg.d/llvm-snapshot.asc
        sudo add-apt-repository -y -n ppa:rbalint/xxhash
        sudo add-apt-repository -y 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
        sudo apt-get -y install clang-tools-9 $BUILD_DEPS
    - name: scan-build
      run: |
        scan-build-9 cmake .
        scan-build-9 --status-bugs make -j2
  clang-build:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: install-deps
      run: |
        sudo cp .github/workflows/llvm-snapshot.gpg.key /etc/apt/trusted.gpg.d/llvm-snapshot.asc
        sudo add-apt-repository -y 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main'
        sudo apt-get -y install clang-tools-9 $BUILD_DEPS
    - name: build
      run: |
        env CXX=clang++ CC=clang cmake .
        # the interceptor does not work when building it with Clang, thus make check always fails
        make -j2
  rebuild-self:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: install-deps
      run: |
        sudo add-apt-repository -y ppa:rbalint/xxhash
        # work around breaking 18.04's make https://github.com/rbalint/fb/issues/174
        sudo apt-get -y install $BUILD_DEPS
        sudo apt-get -y upgrade
    - name: rebuild self
      run: |
        tools/rebuild-self build
        # rebuild again, to test shortcutting
        cd test
        ./run-firebuild make -C ../build clean
        time ./run-firebuild make -C ../build all
        du -sh test_cache_dir
    - name: rebuild self with -j8
      run: |
        cd test
        rm -r test_cache_dir
        ./run-firebuild make -C ../build clean
        time ./run-firebuild make -j8 -C ../build all
        ./run-firebuild make -C ../build clean
        time ./run-firebuild make -j8 -C ../build all

  build-other-projects:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: install-deps
      run: |
        sudo sed -i 's/# deb-src/deb-src/' /etc/apt/sources.list
        sudo apt-get update
        sudo add-apt-repository -y ppa:rbalint/xxhash
        sudo apt-get -y install devscripts $BUILD_DEPS
        sudo apt-get build-dep vte2.91
    - name: build-in-tree
      run: |
        cmake .
        make -j2
    - name: build-vte
      run: |
        apt-get source vte2.91
        cd vte2.91-*
        meson build
        cd ../test
        ./run-firebuild ninja -j8 -C ../vte2.91-*/build

  style-checks:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: install-deps
      run: |
        sudo add-apt-repository -y ppa:rbalint/xxhash
        sudo apt-get -y install $BUILD_DEPS python3-pip
        # TODO(rbalint) use packaged cpplint when it becomes available https://bugs.debian.org/960847
        pip3 install cpplint==1.5.4
    - name: configure
      run: cmake .
    - name: style-check
      run: env PATH=$HOME/.local/bin:$PATH make style-check

