name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install-deps
      run: |
        sudo add-apt-repository -y -u ppa:rbalint/xxhash
        sudo apt-get -y install bats cmake lcov libconfig++-dev libjs-d3 libprotobuf-dev protobuf-compiler libxxhash-dev moreutils valgrind
    - name: build-out-of-tree
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: build-in-tree
      run: |
        cmake .
        make
    - name: test
      # tests don't run with out of tree builds at the moment
      run: |
        make check
        env FIREBUILD_PREFIX_CMD=valgrind make check
    - name: coverage
      # tests don't run with out of tree builds at the moment
      run: |
        git clean -dxf
        cmake -DCOVERAGE=1
        make all check coverage_info
