name: CI

on:
  push:
    branches:
      - shim-debug
  pull_request:
    branches:
      - master

env:
  BUILD_DEPS: cmake libconfig++-dev libevent-dev libflatbuffers-dev flatbuffers-compiler libxxhash-dev libjemalloc-dev libfmt-dev pkg-config python3-jinja2
  TEST_DEPS: bats node-d3 graphviz moreutils fakeroot
jobs:
  build-deb:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: install-deps
      run: |
        sudo add-apt-repository -y ppa:rbalint/xxhash
        sudo eatmydata apt-get build-dep .
    - name: deb
      run: |
        # skip dh_buildinfo step
        printf '\noverride_dh_buildinfo:\n' >> debian/rules
        dpkg-buildpackage -j2 -us -uc
        sudo apt-get install ../*.deb
        firebuild -- ls
