name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
    - uses: actions/checkout@v2
    - name: install-deps
      run: |
        sudo add-apt-repository -y -u ppa:rbalint/xxhash
        sudo apt-get -y install bats cmake doxygen graphviz lcov libconfig++-dev libjs-d3 libprotobuf-dev protobuf-compiler libxxhash-dev moreutils valgrind
    - name: build-out-of-tree
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: doc
      run: |
        cd build
        doxygen
    - name: build-in-tree
      run: |
        cmake .
        make
    - name: test
      # tests don't run with out of tree builds at the moment
      run: |
        make check
        env FIREBUILD_PREFIX_CMD="valgrind -q" make check
    - name: coverage
      # tests don't run with out of tree builds at the moment
      run: |
        git clean -dxf
        # fake d3.js
        touch data/d3.v5.min.js
        cmake -DCOVERAGE=1
        make all check coverage_info
  scan-build:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
    - uses: actions/checkout@v2
    - name: install-deps
      run: |
        sudo add-apt-repository -y -u ppa:rbalint/xxhash
        sudo apt-get -y install clang-tools cmake libconfig++-dev libprotobuf-dev protobuf-compiler libxxhash-dev
    - name: scan-build
      run: |
        scan-build cmake .
        scan-build --status-bugs make
